//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoStop.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.FilaData = new HashSet<FilaData>();
        }
    
        public int ID { get; set; }
        public string Registro { get; set; }
        public int IDUsuario { get; set; }
        public bool Role { get; set; }
        public int IDEstabelecimento { get; set; }
    
        public virtual Estabelecimento Estabelecimento { get; set; }
        public virtual Setor Setor { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilaData> FilaData { get; set; }
    }
}
